systems_list = ("3DO",
                "Atari - 2600",
                "Atari - 7800",
                "Atari - Jaguar",
                "Atari - Lynx",
                "Atari - ST",
                "Bandai - WonderSwan Color",
                "Bandai - WonderSwan",
                "Commodore Amiga",
                "DOOM",
                "DOS",
                "FB Alpha - Arcade Games",
                "GCE - Vectrex",
                "Magnavox - Odyssey2",
                "MAME",
                "Microsoft - MSX",
                "Microsoft - MSX2",
                "NEC - PC Engine - TurboGrafx 16",
                "NEC - PC Engine CD - TurboGrafx-CD",
                "NEC - PC Engine SuperGrafx",
                "NEC - PC-FX",
                "Neo Geo",
                "Nintendo - Famicom Disk System",
                "Nintendo - Game and Watch",
                "Nintendo - Game Boy Advance",
                "Nintendo - Game Boy Color",
                "Nintendo - Game Boy",
                "Nintendo - Nintendo 64",
                "Nintendo - Nintendo DS",
                "Nintendo - Nintendo Entertainment System",
                "Nintendo - Satellaview",
                "Nintendo - Super Nintendo Entertainment System",
                "Nintendo - Virtual Boy",
                "Sega - 32X",
                "Sega - Dreamcast",
                "Sega - Game Gear",
                "Sega - Master System - Mark III",
                "Sega - Mega Drive - Genesis",
                "Sega - Mega-CD - Sega CD",
                "Sega - Saturn",
                "Sega - SG-1000",
                "Sinclair - ZX Spectrum +3",
                "SNK - Neo Geo Pocket Color",
                "SNK - Neo Geo Pocket",
                "Sony - PlayStation Portable",
                "Sony - PlayStation")

emu_dict = {'genesis_plus_gx_libretro.dll': 'Genesis Plus GX',
            'mupen64plus_libretro.dll': 'Mupen64Plus OpenGL',
            'nestopia_libretro.dll': 'Nestopia',
            'snes9x2005_libretro.dll': 'Snes9x 2005',
            'snes9x_libretro.dll': 'Snes9x'
        }